### ISSUE TITLE
可不可以问下在LeanCloud需要做什么工作。

### ISSUE THREAD

**Issue by Loismur** [pgbo/WukongSNS#7]
如果像借鉴这个工程的话，在LeanCloud需要增加什么东西。

**Comment by pgbo** [comment]
不需要，如果你要体验一下 leancloud 怎么用，那么最好在 leancloud 上注册一个开发者账号，然后申请 app key 之类的，在工程的 appdelegate 里替换为自己的 app key。

**Comment by Loismur** [comment]
非常感谢，我去试试LeanCloud
